### ISSUE TITLE
HEAD causes an exception

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/Apktool#2]
## Description

Commit 699d8abf59ca5625240d26d96937bf645336d819 introduced the dependency of this Apktool fork to `revanced-patcher`:
https://github.com/revanced/revanced-patcher/blob/70ca184cf91254731dbb1730be7ff01fd704faec/build.gradle.kts#L30

## Exception

```text
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dan1st\AppData\Local\Temp\brut_util_Jar_118617405104718699394608320940137061030.tmp, compile, --dir, D:\Data\PRGM\Java\revanced-cli\revanced-cache\res, --legacy, -o, D:\Data\PRGM\Java\revanced-cli\revanced-cache\build\resources.zip]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:543)
    at brut.androlib.Androlib.buildResources(Androlib.java:441)
    at app.revanced.patcher.Patcher.save(Patcher.kt:152)
    at app.revanced.cli.Patcher$Companion.start$revanced_cli(Patcher.kt:29)
    at app.revanced.cli.MainCommand.run(MainCommand.kt:88)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at app.revanced.cli.MainKt.main(Main.kt:6)
```

## Exception cause

```text
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dan1st\AppData\Local\Temp\brut_util_Jar_118617405104718699394608320940137061030.tmp, compile, --dir, D:\Data\PRGM\Java\revanced-cli\revanced-cache\res, --legacy, -o, D:\Data\PRGM\Java\revanced-cli\revanced-cache\build\resources.zip]
    at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:386)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:640)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:518)
    ... 13 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dan1st\AppData\Local\Temp\brut_util_Jar_118617405104718699394608320940137061030.tmp, compile, --dir, D:\Data\PRGM\Java\revanced-cli\revanced-cache\res, --legacy, -o, D:\Data\PRGM\Java\revanced-cli\revanced-cache\build\resources.zip]
    at brut.util.OS.exec(OS.java:99)
    at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:382)
    ... 15 more

```

## Temporal workaround (@danthe1st)
```diff
diff --git a/src/main/kotlin/app/revanced/patcher/Patcher.kt b/src/main/kotlin/app/revanced/patcher/Patcher.kt
index 784cde5..c5d9aea 100644
--- a/src/main/kotlin/app/revanced/patcher/Patcher.kt
+++ b/src/main/kotlin/app/revanced/patcher/Patcher.kt
@@ -146,7 +146,7 @@ class Patcher(
         // build modified resources
         if (patchResources) {
             val extDir = ExtFile(resourceCacheDirectory)
-
+            File(resourceCacheDirectory,"build/apk").mkdirs()//make sure this directory exists since Apktool/Androlib does not create it
             // TODO: figure out why a new instance of Androlib is necessary here
             Androlib().buildResources(extDir, usesFramework)
         }
```

## Possible solution

This issue might be fixed if we do not create packages from the master branch but use the latest release tags. The latest one currently `2.6.1`.

**Comment by Sculas** [comment]
This was fixed in 12c490196b4a0e70275cfff3f9584f100c94353b.
